name: Build

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      API_PATH: https://hfx-api.onrender.com
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'

    - name: Make Env File
      run: printf "API_PATH=$API_PATH\n" > .env 

    - name: Install Dependencies
      run: npm ci

    - name: Build
      run: npm run build

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-artifacts
        path: dist
        retention-days: 7
  
  deploy:
    name: Deploy

    needs: build
    
    if: github.ref == 'refs/heads/production'

    runs-on: ubuntu-latest

    steps:
    - name: Download Build Artifacts
      uses: actions/download-artifact@v4
      with:
        name: build-artifacts
        path: dist

    - name: Deploy
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: ftp.stevebunting.com
        username: hfx-github-actions
        password: ${{ secrets.ftp_password }}
        local-dir: ./dist/
